// Date: 9/28/2013 4:10:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.dudu.sieve.blocks.models

import net.minecraft.Entity
import net.minecraft.ModelBase
import net.minecraft.ModelRenderer
import net.minecraft.ResourceLocation

class ModelSieve : ModelBase() {
    //fields
    var Leg1: ModelRenderer
    var Leg2: ModelRenderer
    var Leg3: ModelRenderer
    var Leg4: ModelRenderer
    var BoxSide1: ModelRenderer
    var BoxSide2: ModelRenderer
    var BoxSide3: ModelRenderer
    var BoxSide4: ModelRenderer

    init {
        textureWidth = 128
        textureHeight = 128

        Leg1 = ModelRenderer(this, 0, 0)
        Leg1.addBox(0f, 0f, 0f, 1, 11, 1)
        Leg1.setRotationPoint(-7f, 13f, -7f)
        Leg1.setTextureSize(128, 128)
        Leg1.mirror = true
        setRotation(Leg1, 0f, 0f, 0f)
        Leg2 = ModelRenderer(this, 0, 0)
        Leg2.addBox(0f, 0f, 0f, 1, 11, 1)
        Leg2.setRotationPoint(-7f, 13f, 6f)
        Leg2.setTextureSize(128, 128)
        Leg2.mirror = true
        setRotation(Leg2, 0f, 0f, 0f)
        Leg3 = ModelRenderer(this, 0, 0)
        Leg3.addBox(0f, 0f, 0f, 1, 11, 1)
        Leg3.setRotationPoint(6f, 13f, 6f)
        Leg3.setTextureSize(128, 128)
        Leg3.mirror = true
        setRotation(Leg3, 0f, 0f, 0f)
        Leg4 = ModelRenderer(this, 0, 0)
        Leg4.addBox(0f, 0f, 0f, 1, 11, 1)
        Leg4.setRotationPoint(6f, 13f, -7f)
        Leg4.setTextureSize(128, 128)
        Leg4.mirror = true
        setRotation(Leg4, 0f, 0f, 0f)
        BoxSide1 = ModelRenderer(this, 6, 0)
        BoxSide1.addBox(0f, 0f, 0f, 16, 6, 1)
        BoxSide1.setRotationPoint(-8f, 8f, -8f)
        BoxSide1.setTextureSize(128, 128)
        BoxSide1.mirror = true
        setRotation(BoxSide1, 0f, 0f, 0f)
        BoxSide2 = ModelRenderer(this, 6, 8)
        BoxSide2.addBox(0f, 0f, 0f, 16, 6, 1)
        BoxSide2.setRotationPoint(-8f, 8f, 7f)
        BoxSide2.setTextureSize(128, 128)
        BoxSide2.mirror = true
        setRotation(BoxSide2, 0f, 0f, 0f)
        BoxSide3 = ModelRenderer(this, 6, 16)
        BoxSide3.addBox(0f, 0f, 0f, 1, 6, 14)
        BoxSide3.setRotationPoint(7f, 8f, -7f)
        BoxSide3.setTextureSize(128, 128)
        BoxSide3.mirror = true
        setRotation(BoxSide3, 0f, 0f, 0f)
        BoxSide4 = ModelRenderer(this, 6, 37)
        BoxSide4.addBox(0f, 0f, 0f, 1, 6, 14)
        BoxSide4.setRotationPoint(-8f, 8f, -7f)
        BoxSide4.setTextureSize(128, 128)
        BoxSide4.mirror = true
        setRotation(BoxSide4, 0f, 0f, 0f)
    }

    override fun render(entity: Entity, f: Float, f1: Float, f2: Float, f3: Float, f4: Float, f5: Float) {
        super.render(entity, f, f1, f2, f3, f4, f5)
        setRotationAngles(f, f1, f2, f3, f4, f5, entity)
        Leg1.render(f5)
        Leg2.render(f5)
        Leg3.render(f5)
        Leg4.render(f5)
        BoxSide1.render(f5)
        BoxSide2.render(f5)
        BoxSide3.render(f5)
        BoxSide4.render(f5)
    }

    fun simpleRender(scale: Float) {
        Leg1.render(scale)
        Leg2.render(scale)
        Leg3.render(scale)
        Leg4.render(scale)
        BoxSide1.render(scale)
        BoxSide2.render(scale)
        BoxSide3.render(scale)
        BoxSide4.render(scale)
    }

    private fun setRotation(model: ModelRenderer, x: Float, y: Float, z: Float) {
        model.rotateAngleX = x
        model.rotateAngleY = y
        model.rotateAngleZ = z
    }

    override fun setRotationAngles(f: Float, f1: Float, f2: Float, f3: Float, f4: Float, f5: Float, entity: Entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity)
    }

    companion object {
        @JvmField
        val textures: Array<ResourceLocation> = arrayOf(
            ResourceLocation("sieve", "textures/blocks/sieve.png"),
        )
    }
}
